# Generated by Django 5.2.8 on 2025-11-24 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=100, unique=True)),
                ('project_id', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['project_id'], name='analyzer_ar_project_435224_idx'), models.Index(fields=['article_id'], name='analyzer_ar_article_a08695_idx'), models.Index(fields=['created'], name='analyzer_ar_created_b9459b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='analyzer.article')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['article', 'viewed_at'], name='analyzer_vi_article_b85fcb_idx'), models.Index(fields=['viewed_at'], name='analyzer_vi_viewed__241406_idx')],
                'unique_together': {('article', 'viewed_at')},
            },
        ),
    ]
